spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  profiles:
    active: dev
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cache:
    type: redis
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    allow-circular-references: true
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

sa-token:
  token-name: Authorization
  active-timeout: 2592000
  is-concurrent: true
  is-share: true
  token-style: simple-uuid
  is-color-log: true
